version: '2'
services:
    doctorz-app:
        image: doctorz
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://doctorz-mysql:3306/doctorz?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    doctorz-mysql:
        extends:
            file: mysql.yml
            service: doctorz-mysql
